version: '3.9'

services:
  # Vite client service
  vite:
    build:
      context: ./client
      dockerfile: Dockerfile.vite
    network_mode: host
  # Backend server service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: host
