version: '3.9'

services:
  # Vite client service
  vite:
    build:
      context: ./client # The build context is the current directory
      dockerfile: Dockerfile.vite # Location of the Dockerfile for the Vite client
  # Backend server service
  backend:
    build:
      context: ./server # The build context is the current directory
      dockerfile: Dockerfile # Location of the Dockerfile for the backend server

