version: '3.9'

services:
  # Vite client service
  vite:
    build:
      context: . # The build context is the current directory
      dockerfile: ./client/Dockerfile.vite # Location of the Dockerfile for the Vite client

  # Backend server service
  backend:
    build:
      context: . # The build context is the current directory
      dockerfile: ./server/Dockerfile # Location of the Dockerfile for the backend server

